title: Skyrim Unification Project
description: A modlist for Skyrim Special Edition.
theme: just-the-docs
color_scheme: wakingdreams-dark
back_to_top: true
back_to_top_text: "Back to top"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  skyrimunificationproject

# Build settings


# Pages in following directories will be excluded from the Export
exclude:
  - wip/

search:
  heading_level: 4
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

aux_links:
  "Discord":
    - "https://discord.gg/UAhtyb2XuK"
  "Nexus":
    - "https://www.nexusmods.com/skyrimspecialedition/mods/160547"
  "Wabbajack":
    - "https://www.wabbajack.org"

kramdown:  
  toc_levels: 1..1
    
# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://https://github.com/skyrimunificationproject/skyrimunificationproject.github.io/" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
   
callouts_level: loud
callouts:
  highlight:
    title: Notice
    color: yellow
  important:
    title: Important
    color: yellow
  logfile:
    title: Log Section
    color: green
  iniSetting:
    title: INI Setting
    color: green
  alternative:
    title: Alternative
    color: green
  console:
    title: Console Commands
    color: green    
  hint:
    title: Hint
    color: green  
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red
  NoTitleYellow:
    color: yellow
  NoTitleGreen:
    color: green
    
# Define Jekyll collections
collections:
  # Define a collection named "ClassGuides", its documents reside in the "_ClassGuides" directory
  01Help:
    permalink: "/:collection/:path/"
    output: true
  01Support:
    permalink: "/:collection/:path/"
    output: true
  01HowDoI:
    permalink: "/:collection/:path/"
    output: true
  02ModlistBasics:
    permalink: "/:collection/:path/"
    output: true
  02RecommendedReading:
    permalink: "/:collection/:path/"
    output: true
  02GameplayGuide:
    permalink: "/:collection/:path/"
    output: true
  03Gameplay:
    permalink: "/:collection/:path/"
    output: true
  04Mechanics:
    permalink: "/:collection/:path/"
    output: true
  05ManualInstall:
    permalink: "/:collection/:path/"
    output: true
  06ModlistVersions:
    permalink: "/:collection/:path/"
    output: true

   
just_the_docs:
  collections:
    01Help: # Section 1
      name: Help & Support
      nav_fold: false   
    01Support: # Section 1.A
      name: Support Pages
      nav_hasparent: true
    01HowDoI: # Section 1.B
      name: How Do I?
      nav_hasparent: true
    02RecommendedReading: # Section 2.A
      name: Recommended Reading
      nav_hasparent: true
    02GameplayGuide: # Section 2.B
      name: Gameplay Guide
      nav_hasparent: true
    05ManualInstall: # Section 5
      name: Manual Installation and Modlist Details
      nav_fold: false
    06ModlistVersions: # Section 6
      name: Load Order & Changelogs
      nav_fold: false



  